### ISSUE TITLE
Some .php files not recognized as php

### ISSUE THREAD

**Issue by donut** [derekr/php.sugar#1]
Files that have the .php extension but are basically an HTML file with bits of embedded PHP code here and there are not being recognized as php files, but as HTML files. Since the PHP sugar supports php files with HTML it would be best that these are just taken to be PHP files eve in the case were they contain no PHP whatsoever. At least that's how it seems to me.

**Comment by derekr** [comment]
I do have it set to detect .php files as PHP. I assume you're using the latest sugar yeah?

**Comment by donut** [comment]
Yeah, I'm using v1.0b5.1.

**Comment by donut** [comment]
So, regardless of other content, if a .php file has a doctype specified then it'll be interpreted as HTML even with a .php fil extension. But if it doesn't have a doctype, the .php file is interpreted as PHP.

**Comment by derekr** [comment]
Ok this is because the HTML sugar does a bad job of defining HTML files. It's too general.

I will have this fixed for the next release though.
