### ISSUE TITLE
Standard PHP functions missing from CodeSense  

### ISSUE THREAD

**Issue by mglinski** [derekr/php.sugar#16]
Copied From: http://code.google.com/p/espresso-php-sugar/issues/detail?id=44

There are a number of PHP functions that were not included in the shipping
version of the espresso sugar. I do not know if this has been resolved as
of the current SVN code but using it for 5 mins just trying it out I found
approx. 6 functions that were not included in CodeSense lookups. 

I have encountered this problem with EVERY development environment I have
used, and suffice to say it has become quite annoying. Hope it gets fixed
on this one, as I really like the interface and the suggested roadmap of
this project.
-Matt
## Edit-

I have the list for you of all documented php functions, how should I go about sending you the list?
-Matt

**Comment by mglinski** [comment]
I have hosted the file here: http://rapidshare.com/files/226831372/export.php
It's a php array, array keys are the function names.
Let me know if you need anything else.
-Matt

**Comment by derekr** [comment]
How did you go about parsing the documentation?

**Comment by mglinski** [comment]
If you want I can package up the code I wrote to grab the functions. I used phpQuery and a local copy of the php manual to grab the args list. Let me know if you want it, i'll be happy to share.
-Matt

**Comment by derekr** [comment]
Added functions from documentation.
