### ISSUE TITLE
Better HereDoc Itemizer recipe

### ISSUE THREAD

**Issue by mglinski** [derekr/php.sugar#20]
I was tweaking the heredoc support in the itemizes and eventually arrived at a better selector then what is currently implemented. 
http://www.pastie.org/465531
-Matt

**Comment by derekr** [comment]
I don't see how this is any better. The syntax zone takes care of making sure the delimiters match up, and the goal of the Navigator is to help scan the contents of the sourcecode, not capture every bit of it. Thanks for the submission, but I think I'll leave it as is for now.
