### ISSUE TITLE
Date functions - zone name differs from convention

### ISSUE THREAD

**Issue by davisjr** [derekr/php.sugar#29]
Zone name used for built-in date functions seems to be different from similar zones.

Zone name for other support functions:
    identifier.function.support.*

Eg:
    identifier.function.support.type
    identifier.function.support.fsock

For date functions:
    identifier.function.support_date

Not sure if this was chosen deliberately? 
Anyways, hope it helps!

**Comment by derekr** [comment]
Word. There are so many of them I must have just missed it. Will be fixed in a new revision soon.

**Comment by derekr** [comment]
Went through and updated all the instances of support_ to support.
