### ISSUE TITLE
Do-While loops not recognised correctly

### ISSUE THREAD

**Issue by ghost** [derekr/php.sugar#38]
Hi,

In a project I'm working on, I've been using some do while loops, but they aren't being recognised correctly. For example, the following function:

```
function foo(){
    do {
        /* ... */
    } while (false);
}
```

is recognised as:

```
function foo(){
    do {
        /* ... */
    } // <=== function ends here!?
```

Which can lead to a lot of hierarchical problems when classes and switches are involved. In the syntax xml file, a container.block.dowhile is defined as

```
        <zone name="container.block.dowhile">
            <starts-with>
                <expression>(\bdo(\s)*while\b)\s*(\()</expression>
                <capture number="1" name="keyword.control.flow.dowhile" />
                <capture number="2" name="delimiter.balanced.parenthesis.condition.begin" />
            </starts-with>
            <ends-with>
                <expression>\)</expression>
                <capture number="0" name="delimiter.balanced.parenthesis.condition.end" />
            </ends-with>
            <subzones>
                <include collection="container.block.subzones" />
            </subzones>
        </zone>
```

and this will match

```
dowhile(true){
    /* ... */
}
```

However this is syntactically incorrect and will result in a parse error, so perhaps the zone could be replaced with the following:

```
        <zone name="container.block.dowhile">
            <expression>(\bdo\b)</expression>
            <capture number="1" name="keyword.control.flow.dowhile" />
        </zone>
```

I've been using this and haven't had any problems, it's just like the container.block.try and results in the correct hierarchy in the navigator. This also means that in the CodeSenseLibraries, the `<completion string="dowhile" />` needs to be changed to `<completion string="do" />`.

Hope this helps :)

**Comment by derekr** [comment]
Thanks for the detailed report!

The PHP sugar is being handled internally at Mac Rabbit now. I'll pass this along to them. Once their version is officially in place I'll most likely being removing this project. Just wanted to give you a heads up.
