### ISSUE TITLE
function definitions in CodeSense

### ISSUE THREAD

**Issue by abergs** [derekr/php.sugar#39]
Oh, please please add "user-created functions" in the CodeSense.
It makes no sense why they wouldn't be in the CodeSense. Since you pretty often use your own functions, right?

What are your thoughts of adding this to the Sugar?

**Comment by derekr** [comment]
This sugar is now maintained by Mac Rabbit.

Currently intellisense isn't supported in Espresso for any sugars. Hopefully this is something that changes in the near future.

If you'd like to keep up with the community and submit feature request check out http://wiki.macrabbit.com/forums/.
