### ISSUE TITLE
Comment line with multiple * 

### ISSUE THREAD

**Issue by cwthorpe** [derekr/php.sugar#40]
If you have a comment line such as
/******_/
with multiple '_' and no spaces, then syntax highlighting screws up - it doesn't recognise the end of the comment.

If there is a second similar line it stops the comment highlighting on the last _/
/_*****/

This is a pain for those projects where comment blocks contain such lines - eg PHP-NUKE

**Comment by cwthorpe** [comment]
ok, this is because of the phpDoc comment block definition - it expects the ending */ to be at the start of a line.

Taking the '\s' out of the <ends-with> expression fixes the issue.

**Comment by derekr** [comment]
Hey,

This sugar is currently maintained internally by the MacRabbit crew now. Thanks for lookin' out though. If you find any more issues I'd suggest hitting up their forums: http://wiki.macrabbit.com/forums/.
