### ISSUE TITLE
<?php ?> tags not recognized in comments

### ISSUE THREAD

**Issue by donut** [derekr/php.sugar#6]
So, if one has the following the ?> tag is just seen as part of the comment:

```
<?php if (true) : //this never happens ?>
    echo "GOOMBA!";
<?php endif ?>
```

The first ?> is not recognized as being separate from the comment. This happens in comment blocks as well.

**Comment by derekr** [comment]
I tested this with comment blocks, but couldn't recreate the issue. Only when using the line `//` comment.

**Comment by donut** [comment]
Yeah, that's right. I was a bit confused when I tested it out. It's just the single-line comments that create this issue.

**Comment by derekr** [comment]
Are we sure it should be parsed like that? I have checked other editors and they comment out the ?> as well. It makes sense because `//` comments out the whole line.

**Comment by donut** [comment]
But PHP doesn't care that the whole line is commented out, it still reads the `?>`. This is done all over the Wordpress default template. Block comments do effectively nullify any open/close tags within them, but line comments do not.
