### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by tanc** [derekr/php.sugar#7]
Sorry for asking a noob question, but how is this installed? Previously when downloading from the google code repository I was able to simply double click the downloaded file to install in Espresso. When this gitgub repository is downloaded I can rename the directory to php.sugar and double click that but while it moves the package to the correct location on my filesystem, Espresso doesn't recognise it as a valid sugar. The only way I can get it to work is if I rename the directory 'XML based' to 'php.sugar'. Is this correct?

**Comment by derekr** [comment]
It is now an Xcode project and needs to be compiled. You can download a compiled release in the downloads section. I'll be adding installation directions to the main github page.

**Comment by tanc** [comment]
Ahh... fantastic, thanks Derek. Makes total sense now :-)
