### ISSUE TITLE
Control structure alternate syntax not in Navigator

### ISSUE THREAD

**Issue by donut** [derekr/php.sugar#8]
`if`, `foreach`, `while`, etc control structures that use the alternate syntax (`if (true) : /* stuff */ endif;`) don't show up in the Navigator.

**Comment by derekr** [comment]
Yeah I haven't defined the alternate syntaxes yet. Will be adding those for the next release.

**Comment by derekr** [comment]
I am actually going to schedule this for 1.0b7.
